- name: AWS network infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create or update network stack
    cloudformation:
      stack_name: 'Network'
      state: 'present'
      region: 'ap-southeast-2'
      disable_rollback: true
      template: 'files/network.yml'
      template_parameters:
        VpcName: 'Example'
        VpcCidrBlock: '10.0.0.0/16'
        PublicSubnet1Name: 'Example - Public Subnet A'
        PublicSubnet1CidrBlock: '10.0.0.0/24'
        PublicSubnet1AvailabilityZone: 'ap-southeast-2a'
        PublicSubnet2Name: 'Example - Public Subnet B'
        PublicSubnet2CidrBlock: '10.0.1.0/24'
        PublicSubnet2AvailabilityZone: 'ap-southeast-2b'
        InternetGatewayName: 'Example - Internet Gateway'
        RouteTableName: 'Example - Route Table'
  - name: Create or update ECS cluster stack
    cloudformation:
      stack_name: 'EcsCluster'
      state: 'present'
      region: 'ap-southeast-2'
      disable_rollback: true
      template: 'files/cluster.yml'
      template_parameters:
        ClusterName: 'Example'
  - name: Create or update service stack
    cloudformation:
      stack_name: 'Service'
      state: 'present'
      region: 'ap-southeast-2'
      disable_rollback: true
      template: 'files/service.yml'
      template_parameters:
        NetworkStackName: 'Network'
        ClusterStackName: 'EcsCluster'
        EcsSecurityGroupName: 'ExampleEcs'
        AlbSecurityGroupName: 'ExampleAlb'
        AlbName: 'ExampleAlb'
        ServiceName: 'Example'
        ContainerCpu: '256'
        ContainerMemory: '512'
        ImageUrl: 'nginx'
        DesiredCount: 2
        TargetGroupName: 'ExampleTargetGroup'
