- name: AWS network infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create or update network stack
    cloudformation:
      stack_name: 'Network'
      state: 'present'
      region: 'ap-southeast-2'
      disable_rollback: true
      template: 'files/network.template'
      template_parameters:
        VpcName: 'Example'
        VpcCidrBlock: '10.0.0.0/16'
