- name: AWS network infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create or update network stack
    cloudformation:
      stack_name: 'Network'
      state: 'present'
      region: 'ap-southeast-2'
      disable_rollback: true
      template: 'files/network.template'
      template_parameters:
        VpcName: 'Example'
        VpcCidrBlock: '10.0.0.0/16'
        PublicSubnet1Name: 'Example - Public Subnet A'
        PublicSubnet1CidrBlock: '10.0.0.0/24'
        PublicSubnet1AvailabilityZone: 'ap-southeast-2a'
        PublicSubnet2Name: 'Example - Public Subnet B'
        PublicSubnet2CidrBlock: '10.0.1.0/24'
        PublicSubnet2AvailabilityZone: 'ap-southeast-2b'
        InternetGatewayName: 'Example - Internet Gateway'
        RouteTableName: 'Example - Route Table'
